[package]

name = "rustlearn-5"
version = "0.1.0"
authors = ["sxf <sunxfancy@gmail.com>"]

[[bin]]

name = "rustlearn-5"
path = "main.rs"

[dependencies]
libc = "0.1"
glib = "^0"
gdk = "^0"
gtk = "^0"
cairo-rs = "^0"
